var malts = [
    'Aberfeldy',
    'Aberlour',
    'Abhainn Dearg',
    'Ailsa Bay',
    'Allt-a-Bhainne',
    'An Cnoc',
    'Ardbeg',
    'Ardmore',
    'Arran',
    'Auchentoshan',
    'Auchroisk',
    'Aultmore',
    'Balblair',
    'Balmenach',
    'Balvenie',
    'Ben Nevis',
    'BenRiach',
    'Benrinnes',
    'Benromach',
    'Bladnoch',
    'Blair Athol',
    'Bowmore',
    'Braeval',
    'Bruichladdich',
    'Bunnahabhain',
    'Caol Ila',
    'Cardhu',
    'Clynelish',
    'Cragganmore',
    'Craigellachie',
    'Daftmill',
    'Dailuaine',
    'Dalmore',
    'Dalwhinnie',
    'Deanston',
    'Dufftown',
    'Edradour',
    'Fettercairn',
    'Glenallachie',
    'Glenburgie',
    'Glencadam',
    'Glen Deveron',
    'Glendronach',
    'Glendullan',
    'Glenfarclas',
    'Glenfiddich',
    'Glen Garioch',
    'Glenglassaugh',
    'Glengoyne',
    'Glen Grant',
    'Glenkinchie',
    'Glenlivet',
    'Glenlossie',
    'Glenmorangie',
    'Glen Moray',
    'Glen Ord',
    'Glenrothes',
    'Glen Scotia',
    'Glen Spey',
    'Glentauchers',
    'Glenturret',
    'Highland Park',
    'Inchgower',
    'Inchmurrin',
    'Isle Of Jura',
    'Kilchoman',
    'Kilkerran',
    'Kininvie',
    'Knockando',
    'Lagavulin',
    'Laphroaig',
    'Ledaig',
    'Linkwood',
    'Loch Lomond',
    'Longmorn',
    'Longrow',
    'Macallan',
    'Macduff',
    'Mannochmore',
    'Miltonduff',
    'Mortlach',
    'Oban',
    'Old Pulteney',
    'Pittyvaich',
    'Roseisle',
    'Royal Brackla',
    'Royal Lochnagar',
    'Scapa',
    'Speyburn',
    'Speyside',
    'Springbank',
    'Strathisla',
    'Strathmill',
    'Talisker',
    'Tamdhu',
    'Tamnavulin',
    'Teaninich',
    'Tobermory',
    'Tomatin',
    'Tomintoul',
    'Tormore',
    'Tullibardine'];

module.exports = malts;
